### ISSUE TITLE
Better smoothing functions

### ISSUE THREAD

**Issue by davidsjoberg** [davidsjoberg/ggstream#3]
This is a call to anyone reading this :)

What are the best ways to estimate groups in `ggstream`. Issues:

* All estimated values need to positive.

* Should predict values for the whole datasets x range, not just the group's range.

* Could it converge to zero for leading and dragging x values outside group's x range?

Thanks!

**Comment by jkaupp** [comment]
I'm reading this [paper](http://leebyron.com/streamgraph/stackedgraphs_byron_wattenberg.pdf), which outlines different approaches and methods in streamgraph construction.  Some of these could be implemented keeping in mind the constraints above.

I think the second and third constraints are easily achieved, as each can be dealt with outside of a prediction method.  If the return `NA` they can be set to the baseline.

**Comment by davidsjoberg** [comment]
Yes, thank you! That article seems to have the solution! But also some cool extras (symmetrical/nonsymmetrical for example).

However, I realize that the math could be quite the beast to implement. I will look into it though. And if you want to be a official contributor to the package you are more than welcome to help with the implementation in R.

The main struggle is the relationship between a continous function over the range which i usually estimated and then stack them on top of eachother. In my solution, as you might have seen in the source code I force all group's estimations to all of the x values i want, i.e. the n_grid parameter.

**Comment by jkaupp** [comment]
I have the same concern over the math and I'd need to study it quite a bit in order to figure out exactly how to implement it.  Digging into the JS implementations may help aid in a solution.  I did notice the approach you took with n_grid, and I think it still may work in other cases.  

Happy to be a contributor, and I'll look at the math and the JS implementations in more detail and see what I can make of it.

**Comment by davidsjoberg** [comment]
I skimmed the paper. Very nice and intuitive.

First conclusion. I want all the ordering algorithms in the package!

Second. The math makes a lot of sense, but they all assume a function, but doesn’t explain how to go from real data to a function. For example, I don’t know how to find the slope of a statistical model in R, which is used in the paper.

**Comment by jkaupp** [comment]
Sad that the sorting algorithms weren't outlined.  Might be able to work it out though.

Just a thought, we may not be able to mathematically describe the function, but we can generate the coordinates. Once you get that we can numerically differentiate.

**Comment by davidsjoberg** [comment]
The sorting should be fine I think. Seems intuitive.

Regarding the numeric differentiate, do you have a simple example?

**Comment by jkaupp** [comment]
Did some more digging and [here](https://paolotoffanin.wordpress.com/2017/09/02/streamgraphs-translated-into-r/) is a great post on building them in baseR.   Most of the streamgraph calculations are done via nested for loops.

Regarding numerical differentiation, see [this blog post](https://www.r-bloggers.com/numerical-differentiation-with-finite-differences-in-r/)

**Comment by davidsjoberg** [comment]
Awesome. Then it seems like we got what we need

**Comment by davidsjoberg** [comment]
OK @jkaupp  I looked into the blogposts and I find the example being a bit from what I am aiming at. It seems to be built for well balanced data (streams?). In the real world often data is messy. I have created an example which can be used to plot different predictions. I've added geom_smooth but we want to replace it with the wiggle function outlined in the paper.

library(dplyr)
library(ggplot2)
library(purrr)
set.seed(123)
tibble(x = sample(1:10, 10, replace = T),
       y = accumulate(x, ~.x + rnorm(1, 1, 1), .init = 4)[-1]) %>% 
  ggplot(aes(x, y)) +
  geom_point()+
  ylim(0, NA) +
  geom_smooth(se = F)

**Comment by jkaupp** [comment]
Been working on this off and on.  Got the `themeRiver` method implemented in a `new_stacks` branch on my fork.  I've been using the data generation outlined in their paper (with a different seed).  Will continue to work on the other 3.

``` r
library(tidyverse)
library(ggstream)

bump <- function (a) {
  x <- 1 / (.1 + runif(1, min=0, max=1))
  y <- 2 * runif(1, min=0, max=1) - .5
  z <- 10 / (.1 + runif(1, min=0, max=1))
  n <- length(a) - 1
  i <- 0 : n
  w <- (i / n - y) * z
  a <- a + x * exp(-w * w)
}

set.seed(42)
nStreams = 20
timePoints = 200

values = matrix(0, timePoints, nStreams)
for (icol in 1 : nStreams)
{
  a = matrix(0, 1, timePoints)
  for (i in 1:5)
    a <- bump(a)
  values[, icol] <- a
}

values %>%
  as_tibble() %>%
  mutate(id = row_number()) %>%
  pivot_longer(-id) %>%
  ggplot(aes(x = id, y = value, fill = factor(name))) +
  geom_stream(method = "themeRiver")
#> Warning: The `x` argument of `as_tibble.matrix()` must have column names if `.name_repair` is omitted as of tibble 2.0.0.
#> Using compatibility `.name_repair`.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
```

![](https://i.imgur.com/GH2sWHD.png)

**Comment by davidsjoberg** [comment]
Stunning @jkaupp! Awesome job. I think we're closing in on a good implementation.

I even tested your implementation on real world data. And it works great! And compared to the "true" implementation without smoothing of ThemeRiver. ThemeRiver is very close and is not distorting the interpretation, which my loess and density was doing.

``` r
# PREP -------------------------------------------------------------------------
remotes::install_github('vincentarelbundock/countrycode')
#> Skipping install of 'countrycode' from a github remote, the SHA1 (fe7165ab) has not changed since last install.
#>   Use `force = TRUE` to force installation
pacman::p_load(zoo, ggstream, covid19.analytics, tidyverse,
               hablar, sf, rnaturalearth, patchwork, countrycode,
               naturalearthdata, lubridate)
#> Warning: package 'naturalearthdata' is not available (for R version 3.6.0)
#> Warning in p_install(package, character.only = TRUE, ...):
#> Warning in library(package, lib.loc = lib.loc, character.only = TRUE,
#> logical.return = TRUE, : there is no package called 'naturalearthdata'
#> Warning in pacman::p_load(zoo, ggstream, covid19.analytics, tidyverse, hablar, : Failed to install/load:
#> naturalearthdata
set_wd_to_script_path()
#> Error: RStudio not running
options(scipen = 9999)

world <- ne_countries(scale = 50, returnclass = "sf") %>% 
  select(sovereignt, continent) %>% 
  st_drop_geometry() %>% 
  as_tibble() %>% 
  mutate(name = countryname(sovereignt)) %>% 
  select(-sovereignt)


d <- covid19.analytics::covid19.data("ts-deaths") %>%
  pivot_longer(c(-(1:4)), names_to = "date") %>%
  as_tibble() %>% 
  mutate(name = countryname(Country.Region)) %>% 
  left_join(world)
#> Data being read from JHU/CCSE repository
#> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#> Reading data from https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
#> Data retrieved on 2020-06-15 08:11:59 || Range of dates on data: 2020-01-22--2020-06-14 | Nbr of records: 266
#> --------------------------------------------------------------------------------
#> Joining, by = "name"

d <- d %>% 
  convert(dte(date),
          chr(Country.Region)) %>%
  group_by(continent, date) %>%
  summarise(deaths = sum_(value)) %>%
  group_by(continent) %>%
  arrange(date) %>%
  mutate(deaths = deaths - lag(deaths),
         deaths_r7d = rollmean(deaths, 7, fill = NA, align = "right", na.rm = T)) %>%
  ungroup() %>%
  arrange(continent, date) %>%
  drop_na(deaths_r7d) %>% 
  mutate(continent = factor(continent))

p1 <- ggplot(d, aes(x = date, y = deaths_r7d, fill = factor(continent))) +
  geom_stream(method = "themeRiver") +
  labs(title = "Theme River")
p2 <- ggplot(d, aes(x = date, y = deaths_r7d, fill = factor(continent))) +
  geom_stream(method = "raw") +
  labs(title = "Raw")

p1 / p2 + plot_annotation(title = 'Covid deaths per continent')
```

![](https://i.imgur.com/lD1VwEy.png)

<sup>Created on 2020-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by davidsjoberg** [comment]
@jkaupp Been thinking a bit. 

1. We should focus on the methods you are implementing since they work well and have something of scientific support. So my suggestion is that we remove my loess implementation. Make your Theme River (or if you prefer any of the wiggle-methods more). Maybe keep my density-method for those who want to force start and end to zero for estethic reasons.

2. I opened a new issue regarder factor order. Right now it seems random in what order groups are stacked. By default it should reflect the legend order. When we have fixed that we can implement the factor sorting algorithms. They should be fairly straight forward. I think the sorting algorithm should be part of the geom rather than a function outside ggplot that creates correct factor orders.

**Comment by jkaupp** [comment]
@davidsjoberg, I finished porting the other functions to the new_stacks branch.  

1. I think keeping density and raw from your implementation would be helpful.  I'll eventually work them into a single build or compute_stacks function if possible.  I've also added the 'zero' implementation from the blog, which is just a stacked streamgraph with a zero baseline.

``` r
library(ggplot2)
library(ggstream)
library(patchwork)
library(purrr)

methods <- c("density", "raw", "base", "themeRiver", "newWiggle", 'minimizedWiggle')

streams <- function(x) {

  ggplot(mtcars, aes(x = qsec, y = drat, fill = factor(cyl))) +
    geom_stream(method = x, show.legend = FALSE) +
    labs(title = x)

}

plots <- map(methods, streams)

wrap_plots(plots)
```

![](https://i.imgur.com/v2uCkba.png)

<sup>Created on 2020-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

2. By factor order, do you mean the order of how the streams are stacked should match the order of the legend?  E.g. top legend entry is the top of the stream and following the order down?  I am having trouble seeing how that would work with discontinuous series.

3. While interesting, I think you want to keep any summarizing/roll-up functionality in the domain of data manipulation. This way you don't duplicate any functionality or inflate the package as most of that can be done with dplyr.  It also doesn't conflate the aims of the package which is plotting streamgraphs, not aggregating or summarizing data.

**Comment by Rohit-Satyam** [comment]
Hi @jkaupp @davidsjoberg, I was wondering if these methods got are available in `geom_stream` function or not because the documentation says `Only 'new wiggle' is implemented so far.`.
